### ISSUE TITLE
Unable to get matching results.

### ISSUE THREAD

**Issue by raats31** [shashwatak/satellite-js#34] opened 2017-09-28 13:39 UTC
I have seen all the comments on this [issue](https://github.com/shashwatak/satellite-js/issues/3) and tried all but couldn't resolve my issue, so I am opening a new issue as it's urgent for me to get it resolved

Maybe there is some understanding issue because of which I am not able to generate correct results. Please help me regarding this.

I have compared the results with AGI STK Desktop application. [AGI STK Help Page](http://help.agi.com/stk/index.htm#stk/vehSat_orbitProp_msgp4.htm) says 

>By default, STK utilizes the CSSI SGP4 routine, Version 2008-11-03. 

Following is the full description of my usage:

TLE Data: 
```
1 20959U 90103A   14044.72615235  .00000027  00000-0  00000+0 0  2724 
2 20959  54.3261 214.0472 0115346 348.3774  11.3322  2.00583365170051
```

ECI Data generated from AGI STK software: 
```
Time (UTCG)                    x (km)            y (km)       z (km) 
28 Jul 2017 02:55:06.000    -6749.036399    -14064.485321    21282.805742
28 Jul 2017 02:55:07.000    -6745.397433    -14065.853241    21283.102965
28 Jul 2017 02:55:08.000    -6741.758320    -14067.220855    21283.399727
28 Jul 2017 02:55:09.000    -6738.119061    -14068.588164    21283.696028
28 Jul 2017 02:55:10.000    -6734.479656    -14069.955168    21283.991866
28 Jul 2017 02:55:11.000    -6730.840105    -14071.321867    21284.287243
28 Jul 2017 02:55:12.000    -6727.200408    -14072.688260    21284.582158
28 Jul 2017 02:55:13.000    -6723.560565    -14074.054349    21284.876612
28 Jul 2017 02:55:14.000    -6719.920576    -14075.420132    21285.170603
28 Jul 2017 02:55:15.000    -6716.280441    -14076.785610    21285.464134
```

My Code( using satellite.js):
```
updateEntityToCurrentSimTime: function (time) {
        var date = new Date( "07/28/2017 08:25:05");
        var tleLines = ["1 20959U 90103A   14044.72615235  .00000027  00000-0  00000+0 0  2724",
                        "2 20959  54.3261 214.0472 0115346 348.3774  11.3322  2.00583365170051"];
                         
        var satrec = satellite.twoline2satrec(tleLines[0], tleLines[1]);         

        //update current date
        date.setSeconds(date.getSeconds() + time);            

        var gmst = satellite.gstimeFromDate(date);
                        
        var posAndVelECI = satellite.propagate(satrec, date);
}
````
ECI data from my code:
```
28 Jul 2017 02:55:06 GMT    -6729.586681293093    -14090.192704493444    21271.96936623743
28 Jul 2017 02:55:07 GMT    -6725.942904316204    -14091.546319840401    21272.272757457347
28 Jul 2017 02:55:08 GMT    -6722.298834777501    -14092.899684035754    21272.57569941536
28 Jul 2017 02:55:09 GMT    -6718.654766124882    -14094.252688097995    21272.87816771835
28 Jul 2017 02:55:10 GMT    -6715.010551711341    -14095.605386498912    21273.18017456913
28 Jul 2017 02:55:11 GMT    -6711.366191662034    -14096.9577791936    21273.481719959364
28 Jul 2017 02:55:12 GMT    -6707.721686056604    -14098.309866154083    21273.782803884547
28 Jul 2017 02:55:13 GMT    -6704.077034974806    -14099.661647352345    21274.083426340152
28 Jul 2017 02:55:14 GMT    -6700.432238496194    -14101.013122760447    21274.383587321685
28 Jul 2017 02:55:15 GMT    -6696.787150063399    -14102.364346701132    21274.683298872136
```

**Comment by ezze** [comment] 2017-11-19 16:41
@raats31, I was able to reproduce your results with `satellite.js` but, unfortunatelly, I'm out of idea how to get results with AGI STK Desktop application. Is it freeware?

Looking at difference between given results I see that they become close to each other if we suppose that results from STK application are calculated starting since 2017-07-28T02:55:00 but not since 2017-07-28T02:55:06. Is it possible that something was wrong with your input data? Just an assumption.

Have you tried to make similar calculations with original [C++](http://www.celestrak.com/publications/AIAA/2006-6753/) or [Python](https://pypi.python.org/pypi/sgp4/) libraries? `satellite.js` is a port of Python library so corresponding calculations should be as close as possible. I'm not sure which version of the library @shashwatak has ported but today its homepage states that it uses SGP4 version of 2010.

[Recent research](https://github.com/shashwatak/satellite-js/issues/26#issuecomment-285744099) provided by @tikhonovits with C++ library and further [bugfix](https://github.com/shashwatak/satellite-js/pull/37) state that results received by `satellite.js` match calculations made with original library.

**Comment by tikhonovits** [comment] 2017-11-19 19:32
Dear @raats31, further to @ezze response, I suspect that since the results you have got from STK seem to be close, but not identical, to the ones you have got with satellite.js, the former ones probably correspond to a different ECI reference frame that should be the J2000.0. Try to extract similar results for TEME with STK and check for matching. I have tried that before and I found that there was a perfect match between them. Also please [check FAQ no. 7 here](http://celestrak.com/columns/v04n05/index.asp#FAQ07), with respect to the reference frame the results from satellite.js are.

**Comment by ezze** [comment] 2017-11-19 19:51
Seems that [this one](https://github.com/joshuaferrara/node-sgp4/issues/4) is a related issue.

**Comment by ezze** [comment] 2018-01-22 19:38
Closing this as invactive. @raats31, if you still have some issues please feel free to open the new ones.

**Closed by ezze** 2018-01-22 19:38 UTC
